services:
  mysql_db:
    image: mysql:8.0
    container_name: inmeta-mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root_password_123' 
      MYSQL_DATABASE: 'inmeta_docs_db'
    ports:
      - "3306:3306"
    volumes:
      - inmeta-mysql-data:/var/lib/mysql

volumes:
  inmeta-mysql-data: